[server]
port = 8501
headless = true
runOnSave = true
allowedServerAddresses = ["localhost", "127.0.0.1", "10.48.66.38"]
enableXsrfProtection = false
enableCORS = false

[client]
showErrorDetails = false
toolbarMode = "viewer"
showSidebarNavigation = true

[theme]
base                     = "light"
primaryColor             = "#C8102E"
backgroundColor          = "#F0F0F0"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1A1A1A"
font                     = "sans serif"

[browser]
gatherUsageStats = false
